apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-deployment
  template:
    metadata:
      labels:
        app: django-deployment
    spec:
      containers:
        - name: teste
          image: 391486104729.dkr.ecr.us-east-1.amazonaws.com/teste:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi